
export interface Material {
  sku: string;
  description: string;
  boxesPerPallet?: number;
}

export interface PalletItem {
  id: string;
  sku: string;
  description: string; // Copied from master at time of addition to preserve history
  quantity: number;
  deliveryNumber: string;
  tripNumber: string;
  note?: string;
}

export enum PalletStatus {
  OPEN = 'ABIERTO',
  CLOSED = 'CERRADO'
}

export interface Pallet {
  id: string;
  number: number; // Human readable ID
  reference?: string; // Editable reference/client info
  items: PalletItem[];
  status: PalletStatus;
  createdAt: string;
  closedAt?: string;
  aiSummary?: string; // Generated by Gemini
}

export interface ActivityLog {
  id: string;
  timestamp: string;
  action: string;
  details?: string;
  type: 'INFO' | 'SUCCESS' | 'WARNING' | 'DANGER';
}

export type ViewState = 'DASHBOARD' | 'MATERIALS' | 'PALLET_DETAIL' | 'PRINT_PREVIEW' | 'CONSOLIDATED_REPORT' | 'ACTIVITY_HISTORY';
