
export interface Material {
  sku: string;
  description: string;
  boxesPerPallet?: number;
}

export interface PalletItem {
  id: string;
  sku: string;
  description: string; // Copied from master at time of addition to preserve history
  quantity: number;
  deliveryNumber: string;
  tripNumber: string;
  note?: string;
}

export enum PalletStatus {
  OPEN = 'ABIERTO',
  CLOSED = 'CERRADO',
  SENT = 'ENVIADO',
  REMITTED = 'REMITIDO'
}

export interface Pallet {
  id: string;
  number: number; // Human readable ID
  reference?: string; // Editable reference/client info
  items: PalletItem[];
  status: PalletStatus;
  createdAt: string;
  closedAt?: string;
  sentAt?: string;
  containerId?: string;
  aiSummary?: string; // Generated by Gemini
  warehouse?: 'CENTRAL' | 'LA_RURAL';
  remitoNumber?: string;
  remitoDate?: string;
  remitoId?: string;
}

export interface RuralRemito {
  id: string;
  number: number;
  remitoNumber: string; // User-defined or generated consignment number
  createdAt: string;
  palletIds: string[];
  note?: string;
  carrier?: string;
}

export interface Container {
  id: string;
  number: number;
  dispatchId: string; // User friendly ID for the dispatch
  createdAt: string;
  palletIds: string[];
  note?: string;
}

export interface ActivityLog {
  id: string;
  timestamp: string;
  action: string;
  details?: string;
  type: 'INFO' | 'SUCCESS' | 'WARNING' | 'DANGER';
}

export type ViewState = 'DASHBOARD' | 'RURAL_WAREHOUSE' | 'MATERIALS' | 'PALLET_DETAIL' | 'PRINT_PREVIEW' | 'CONSOLIDATED_REPORT' | 'ACTIVITY_HISTORY' | 'CONTAINER_LIST' | 'INVENTORY_COMPARISON';
